name: Chromatic Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  pr_test:
    name: Pull Request Chromatic Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npx chromatic -b build:storybook --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
