name: Continuos Integration

on:
  push:
    branches: [master]

jobs:
  master_test:
    name: Chromatic Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn chromatic -b build:storybook --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --auto-accept-changes
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn test
